app:
  candidate:
    name: "Shaik Shafa Afrin"
    regNo: "22BCE9523"
    email: "you@example.com"
  endpoints:
    base: "https://bfhldevapigw.healthrx.co.in"
    generate: "/hiring/generateWebhook/JAVA"
    submitFallback: "/hiring/testWebhook/JAVA"
  sql:
    q1: "classpath:sql/question1.sql"
    q2: "classpath:sql/question2.sql"
  output:
    storeFile: "solution.sql"

spring:
  main:
    web-application-type: none
logging:
  level:
    root: INFO
    com.example.bfh: DEBUG
